# Generated by Django 4.2 on 2023-04-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('teacher', models.CharField(max_length=40)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField()),
                ('login', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('email', 'teacher', 'login', 'password', 'age', 'name')},
            },
        ),
    ]
