# Generated by Django 4.0.2 on 2023-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_shop_description_alter_project_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='additionals',
            field=models.ManyToManyField(blank=True, null=True, to='base.Image', verbose_name='Дополнительные изображения'),
        ),
    ]
